version: '3'

services:
  minio:
    image: minio/minio
    network_mode: host
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - '/mnt/data:/data'
    command: server /data --console-address ":9001"

  postgres:
    image: postgres
    network_mode: host
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - '/mnt/postgres:/var/lib/postgresql/data'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - postgres
    volumes:
      - './backend:/app'

  web:
    image: python:3.9-slim
    network_mode: host
    volumes:
      - './fe:/app/fe'
    command: 'python -m http.server -d /app 8010'
